let HamburgerMenuData = [
  {
    id: 1,
    title: "فرانت اند",
    children: [
      { title: "آموزش HTML", path: "/" },
      { title: "آموزش CSS", path: "/" },
      { title: "آموزش FlexBox", path: "/" },
      { title: "آموزش CSS Grid", path: "/" },
      { title: "مینی پروژه های تخصصی با Css", path: "/" },
      { title: "آموزش Tailwind CSS", path: "/" },
      { title: "آموزش اصولی طراحی قالب", path: "/" },
      { title: "آموزش بوت استرپ", path: "/" },
      { title: "آموزش جاوااسکریپت", path: "/" },
      { title: "پروژه های تخصصی با JS", path: "/" },
      { title: "آموزش جامع ری اکت ReactJS", path: "/" },
      { title: "آموزش ویو جی اس", path: "/" },
      { title: "آموزش وی اس کد - Vscode", path: "/" },
    ],
  },
  {
    id: 2,
    title: "امنیت",
    children: [
      { title: "نقشه راه ورود به دنیای هک و امنیت", path: "/" },
      { title: "شبکه با گرایش امنیت", path: "/" },
      { title: "لینوکس با گرایش امنیت", path: "/" },
      { title: "آموزش هکر قانونمند - CEH VII", path: "/" },
      { title: "آموزش کالی لینوکس", path: "/" },
      { title: "آموزش پایتون سیاه", path: "/" },
      { title: "آموزش Burb Suite", path: "/" },
      { title: "آموزش جاوااسکریپت سیاه", path: "/" },
    ],
  },
  {
    id: 3,
    title: "پایتون",
    children: [
      { title: "دوره آموزش پایتون", path: "/" },
      { title: "پروژه های کاربردی با پایتون", path: "/" },
      { title: "بهینه نویسی کد ها در پایتون", path: "/" },
      { title: "متخصص جنگو", path: "/" },
      { title: "مصور سازی داده با پایتون", path: "/" },
    ],
  },
  {
    id: 4,
    title: "پی اچ پی",
    children: [
      { title: "ربات تلگرام با PHP", path: "/" },
      { title: "پروژه های کاربردی با PHP", path: "/" },
    ],
  },
  {
    id: 5,
    title: "ارتقای مهارت ها",
    children: [
      { title: "الگوریتم و ساختمان داده", path: "/" },
      { title: "آموزش websocket", path: "/" },
      { title: "گیت و گیت هاب", path: "/" },
      { title: "آموزش GraphQL", path: "/" },
      { title: "توسعه کتابخانه با JS", path: "/" },
      { title: "افزونه نویسی با JS", path: "/" },
      { title: "Clean Code برای JS", path: "/" },
      { title: "دیپلوی پروژه های JS", path: "/" },
      { title: "دوره Mern Stack", path: "/" },
      { title: "آموزش رجکس (regex)", path: "/" },
      { title: "NPM برای جاوااسکریپت کارها", path: "/" },
      { title: "آموزش کاربردی Vscode", path: "/" },
    ],
  },
  {
    id: 6,
    title: "مقالات",
    children: [
      { title: "اچ تی ام ال", path: "/" },
      { title: "بوت استرپ", path: "/" },
      { title: "پروژه های برنامه نویسی", path: "/" },
      { title: "تست نفوذ و امنیت وب", path: "/" },
      { title: "جی کوئری", path: "/" },
      { title: "ری اکت جی اس", path: "/" },
      { title: "سی اس اس", path: "/" },
      { title: "شروع برنامه نویسی", path: "/" },
      { title: "طراحی سایت", path: "/" },
      { title: "ویو جی اس", path: "/" },
    ],
  },
];

export default HamburgerMenuData;
