import cleanCodeImg from "./image/clean-code.webp";
import dashboardImg from "./image/dashboard-herfeee.webp";
import deeoloyImg from "./image/deeploy.webp";
import liveVierMasterImg from "./image/live-vier-master.webp";
import masterFreeLanceImg from "./image/master-freelance.webp";
import miniProjectPytonImg from "./image/mini-project-pyton.webp";
import jangoImg from "./image/motekhasses-jango.webp";
import motekhassesNextImg from "./image/motekhasses-next.webp";
import motekhassesNodejsImg from "./image/motekhasses-nodejs.webp";
import phpImg from "./image/php.webp";
import robotTelegramImg from "./image/robot-telegram.webp";
import afzooneMororGarImg from "./image/afzoone-mororgar.webp";
import cssImg from "./image/css.webp";
import htmlImg from "./image/html5.webp";
import htmlCssImg from "./image/html-css.webp";
import jsSiahImg from "./image/java-script-siah.webp";
import toseeKetabKhaneImg from "./image/tosee-ketab-khane.webp";
import tailwind from "./image/tailwind.webp";
import jsLibrary from "./image/20-js-library.webp";
import canvas from "./image/canvas.webp";
import redux from "./image/redux.webp";
import jsProject from "./image/project-takhasosi-js.webp";
import pwa from "./image/pwa.webp";
import shoroFront from "./image/shoro-front.webp";
import typeScript from "./image/typscript.webp";
import vorodBeAmniyat from "./image/vorod-be-donya-amniyat.webp";
import testNofoz from "./image/test-nofoz-ba-kali-linox.webp";
import amozeshLinux from "./image/amozesh-linux.webp";
import amozeshShabake from "./image/Amozesh-shabake-ba-gerayesh.webp";
import doreHakere from "./image/dore-hacker-ghanoonmand.webp";
import burpSuite from "./image/Amoozesh-abzar-burp-suite.webp";
import amozeshPythonBaGerayesh from "./image/Amoozesh-python-ba-gerayesh-amniat.webp";
import algoritmImg from "./image/algoritm.webp";
import gridImg from "./image/css-grid.webp";
import flexBoxImg from "./image/flex-box.webp";
import graphQlImg from "./image/graphQL.webp";
import hakerImg from "./image/haker.webp";
import laravelImg from "./image/laravel.webp";
import motekhassesJsImg from "./image/motekhasses-javascript.webp";
import motekhassesPytonImg from "./image/motekhasses-pyton.webp";
import webSocketImg from "./image/web-socket.webp";
import DataVisualization from "./image/ezgif.com-jpg-to-webp-converted-19-1-768x432.webp";
import behinePython from "./image/IMAGE-1402-11-04-18_57_18-1-768x432.webp";
import pythonProject from "./image/ezgif.com-jpg-to-webp-converted-10-1-768x432.webp";
import algoritmBeZabanSade from "./image/Amozesh-algoritm-be-zaban.webp";
import git from "./image/git.webp";
import mernStack from "./image/ezgif.com-jpg-to-webp-converted-24-1-768x432.webp";
import regex from "./image/Com_regex-1-768x432.webp";
import npm from "./image/Com_npm-1-768x432.webp";
import vsCode from "./image/Com_VsCode-1-768x432.webp";

let CoursesData = [
  {
    id: 1,
    tag1: "ارتقای مهارت",
    title: "Clean Code برای برنامه نویسان JS",
    desc: "فرق بین یه برنامه نویس تازه کار و حرفه ای نوع دیدگاه و طرز کدنویسیشونه. برنامه نویس...",
    name: "محمد امین سعیدی راد",
    time: "02:21",
    price: 1_100_000,
    member: 234,
    image: cleanCodeImg,
    link: "/frontend",
    type: "",
  },
  {
    id: 2,
    tag1: "بک اند",
    tag2: "پی اچ پی",
    title: "پروژه های کاربردی با PHP",
    desc: '"مینی پروژه‌های کاربری با PHP" یه دوره آموزشی گام به گام هست که برای توسعه‌دهندگان وب،',
    name: "معین باغشیخی",
    time: "09:05",
    price: 470_000,
    member: 6941,
    image: phpImg,
    type: "",
  },
  {
    id: 3,
    tag1: "بک اند",
    title: "آموزش حرفه ای NodeJS بدون پیش نیاز",
    desc: "الان و امروز کمتر کسی هست که از بازار کار داغ نود جی اس با خبر نباشه و یکی از…",
    name: "محمد امین سعیدی راد",
    time: "62:00",
    price: 4_350_000,
    member: 425,
    image: motekhassesNodejsImg,
    type: "",
  },
  {
    id: 4,
    tag1: "فرانت اند",
    title: "آموزش Next.js بصورت پروژه محور",
    desc: "نکست یه فریمورک مبتنی بر ری‌اکت هست که امروزه تو بازار کار یکی از مهم‌ترین تکنولوژی‌ها...",
    name: "محمد امین سعیدی راد",
    time: "32:04",
    price: 2_100_000,
    member: 1369,
    image: motekhassesNextImg,
    type: "frontend",
  },
  {
    id: 5,
    tag1: "پایتون",
    title: "پروژه های کاربردی با پایتون",
    desc: "قبل از اینکه بخواین این دوره رو ببینید اگر دوره آموزش پایتون رو ندیدین حتما دوره رو ببینید",
    name: "رضا دولتی",
    time: "15:17",
    price: 990_000,
    member: 1318,
    image: miniProjectPytonImg,
    type: "",
  },
  {
    id: 6,
    tag1: "فرانت اند",
    title: "پیاده سازی داشبورد های حرفه ای با CSS و JS",
    desc: "این دوره فرصتی فوق‌العاده برای ارتقاء مهارت‌های فرانت اند شماست. با یادگیری از جدیدترین",
    name: "مهرشاد براتی",
    time: "07:08",
    price: 620_000,
    member: 284,
    image: dashboardImg,
    type: "frontend",
  },
  {
    id: 7,
    tag1: "ارتقای مهارت",
    tag2: "فرانت اند",
    title: "توسعه افزونه مرورگر با جاوااسکریپت",
    desc: "ما در این دوره، توسعه افزونه های مرورگر رو با پیاده سازی پروژه های کاربردی با دانش فرانت اند",
    name: "مهرشاد براتی",
    time: "00:00",
    price: 790_000,
    member: 58,
    image: afzooneMororGarImg,
    type: "frontend",
    pishforoush: true,
  },
  {
    id: 8,
    tag1: "بک اند",
    tag2: "پی اچ پی",
    title: "آموزش ساخت ربات تلگرام با PHP",
    desc: 'توی دوره فوق‌العاده جذاب و کاربردی "ربات تلگرام با PHP"، به دنیای عجیب و جذاب ربات نویسی...',
    name: "معین باغشیخی",
    time: "00:22",
    price: 450_000,
    member: 168,
    image: robotTelegramImg,
    type: "",
  },
  {
    id: 9,
    tag1: "بک اند",
    tag2: "پایتون",
    title: "دوره پروژه محور متخصص جنگو",
    desc: "از ویژگی های مهم دوره آموزش جنگو میتونیم به توضیح کامل مفاهیم پایه و ساختاری، کامل..",
    name: "رضا دولتی",
    time: "46:11",
    price: 3_500_000,
    member: 477,
    image: jangoImg,
    type: "",
  },
  {
    id: 10,
    tag1: "مهارت های نرم",
    title: "مستر فریلنس - هنر همکاری موفق با کارفرماها",
    desc: "موفق بودن یک وکیل به تعداد بالای پرونده هاش نیست. بلکه به تعداد کیفیت پرونده...",
    name: "قدیر یلمه",
    time: "00:00",
    price: 7_100_000,
    member: 424,
    image: masterFreeLanceImg,
    type: "",
  },
  {
    id: 11,
    tag1: "ارتقای مهارت",
    title: "زیر و بَم و منطق دیپلوی برای برنامه نویسان JS",
    desc: "تو هر فیلدی فعالیت بکنی برای پرزنت خودت تو بازار کار و نمایش نمونه کارات نیاز به دپلوی",
    name: "محمد امین سعیدی راد",
    time: "00:19",
    price: 700_000,
    member: 221,
    image: deeoloyImg,
    type: "",
  },
  {
    id: 12,
    tag1: "بک اند",
    tag2: "پی اچ پی",
    title: "دوره پروژه محور لایووایر (Livewire Master)",
    desc: "دوره لایووایر مستر (Livewire Master) یک دوره‌ی تمام عیار برای فول‌استک فریمورکِ لایووایر است که هدف آن آموزش قدم به…",
    name: "آرمین هوشمند",
    time: "00:21",
    price: 699_000,
    member: 24,
    image: liveVierMasterImg,
    type: "",
  },
  {
    id: 13,
    tag1: "ارتقای مهارت",
    tag2: "فرانت اند",
    title: "توسعه کتابخانه با جاوااسکریپت",
    desc: "توسعه کتابخانه، نمونه کاری قوی برای رزومه شما است و این دوره آموزشی یادگیری چنین مهارتی...",
    name: "مهرشاد براتی",
    time: "00:00",
    price: 1_100_000,
    member: 39,
    image: toseeKetabKhaneImg,
    type: "frontend",
    pishforoush: true,
  },
  {
    id: 14,
    tag1: "فرانت اند",
    title: "آموزش ۲۰ کتابخانه کاربردی ReactJS برای بازارکار",
    desc: "‌کتابخانه‌ها باعث افزایش سرعت کدنویسی میشن. در حدی که تو بازار کار هم از کتابخانه...",
    name: "محمد امین سعیدی راد",
    time: "14:39",
    price: 570_000,
    member: 1282,
    image: jsLibrary,
    type: "frontend",
  },
  {
    id: 15,
    tag1: "فرانت اند",
    title: "آموزش جامع و پروژه محور Tailwind css",
    desc: "tailwind css یک فریمورک Utility First هست، این فریمورک متشکل از یکسری کلاس های آماده...",
    name: "حمیدرضا عبادی",
    time: "21:28",
    price: 780_000,
    member: 1110,
    image: tailwind,
    type: "frontend",
  },
  {
    id: 16,
    tag1: "فرانت اند",
    title: "مینی پروژه های تخصصی با Html، Css + دیزاین اختصاصی",
    desc: "عنوان دوره گویای همه چی هست اما نیازه برخی موارد گفته بشه تا بتونید با دید بهتری تو این",
    name: "حمیدرضا عبادی",
    time: "00:33",
    price: 720_000,
    member: 387,
    image: htmlCssImg,
    type: "frontend",
  },
  {
    id: 17,
    tag1: "فرانت اند",
    title: "آموزش PWA بصورت پروژه محور",
    desc: "کلمه PWA مخفف Progressive Web App بوده و یه تکنولوژی تقریبا جدیده که میتونیم...",
    name: "محمد امین سعیدی راد",
    time: "11:33",
    price: 1_710_000,
    member: 471,
    image: pwa,
    type: "frontend",
  },
  {
    id: 18,
    tag1: "فرانت اند",
    title: "آموزش تخصصی Redux مقدماتی تا پیشرفته",
    desc: "ریداکس یه کتابخونه پراستفاده واسه مدیریت حالت های مختلف یه برنامه جاوا اسکریپتیه که...",
    name: "محمد امین سعیدی راد",
    time: "12:04",
    price: 1_400_000,
    member: 1201,
    image: redux,
    type: "frontend",
  },
  {
    id: 19,
    tag1: "فرانت اند",
    title: "آموزش Canvas برای برنامه نویسان فرانت‌اند",
    desc: "Canvas عمدتا برای پیاده سازی و رسم نمودار های مختلف جهت تحلیل اطلاعات، بک‌گراندها ...",
    name: "محمد امین سعیدی راد",
    time: "09:01",
    price: 442_500,
    member: 490,
    image: canvas,
    type: "frontend",
  },
  {
    id: 20,
    tag1: "فرانت اند",
    title: "پروژه های تخصصی با جاوا اسکریپت برای بازار کار",
    desc: "هیچ فرقی نمیکنه شما با چه کتابخونه یا فریمورکی کار میکنین. تو این دوره یاد میگیری به...",
    name: "محمد امین سعیدی راد",
    time: "45:08",
    price: 945_000,
    member: 1043,
    image: jsProject,
    type: "frontend",
  },
  {
    id: 21,
    tag1: "فرانت اند",
    title: "آموزش کاربردی Typescript بصورت پروژه محور",
    desc: "تایپ اسکریپت یه زبون برنامه نویسیه که توسط مایکروسافت ارائه شده و یسری قابلیت و فیچر...",
    name: "محمد امین سعیدی راد",
    time: "14:01",
    price: 2_399_000,
    member: 427,
    image: typeScript,
    type: "frontend",
  },
  {
    id: 22,
    tag1: "فرانت اند",
    title: "آموزش Css رایگان مقدماتی تا پیشرفته",
    desc: "تا اینجای کار با HTML آشنا شدی و میتونی اسکلت یه سایتو پیاده کنی دمت گرم. یه قدم...",
    name: "حمیدرضا عبادی",
    time: "12:42",
    price: "رایگان",
    member: 39008,
    image: cssImg,
    type: "frontend",
  },
  {
    id: 23,
    tag1: "فرانت اند",
    title: "آموزش HTML رایگان مقدماتی تا پیشرفته",
    desc: "اولین قدم شروع طراحی وبسایت، آموزش HTML هست. HTML یه زبان نشانه گذاری هست که ب...",
    name: "حمیدرضا عبادی",
    time: "07:37",
    price: "رایگان",
    member: 43920,
    image: htmlImg,
    type: "frontend",
  },
  {
    id: 24,
    tag1: "فرانت اند",
    title: "شروع فرانت اند وب + مثال های جامع و زنده",
    desc: "اگه میخوای طراحی وب رو اصولی شروع کنی و با اصطلاحات  و مقدمات این حوزه آشنا نیستی !...",
    name: "محمد امین سعیدی راد",
    time: "02:13",
    price: "رایگان",
    member: 14444,
    image: shoroFront,
    type: "frontend",
  },
  {
    id: 25,
    tag1: "امنیت",
    title: "ورود به دنیای امنیت | هکر صفر کیلومتر",
    desc: "اگر برای ورود به دنیای امنیت سردرگم هستید. این دوره با راهنمایی مختصر و مفید و ارائه موارد...",
    name: "اشکان مقدس",
    time: "00:35",
    price: "رایگان",
    member: 4690,
    image: vorodBeAmniyat,
    type: "security",
  },
  {
    id: 26,
    tag1: "امنیت",
    title: "تست نفوذ با کالی لینوکس - PWK [سناریو محور]",
    desc: "ما در این دوره قرار هست که kali linux رو با یک دیدگاه متفاوت. بصورت عملی و کاملا سناریو...",
    name: "اشکان مقدس",
    time: "18:54",
    price: 1_300_000,
    member: 453,
    image: testNofoz,
    type: "security",
  },
  {
    id: 27,
    tag1: "امنیت",
    title: "اموزش لینوکس با گرایش امنیت",
    desc: "بعد از دوره شبکه. دومین و مهم ترین دوره ای که برای ورود به دنیای امنیت مشاهده کنید...",
    name: "اشکان مقدس",
    time: "07:44",
    price: 436_500,
    member: 762,
    image: amozeshLinux,
    type: "security",
  },
  {
    id: 28,
    tag1: "امنیت",
    title: "آموزش شبکه با گرایش امنیت | Black Network",
    desc: "دنیای هک و امنیت به اندازه کافی پر چالش و جذاب هست و اگرشما بخواید وارد این حوزه...",
    name: "اشکان مقدس",
    time: "05:13",
    price: 481_500,
    member: 1001,
    image: amozeshShabake,
    type: "security",
  },
  {
    id: 29,
    tag1: "امنیت",
    title: "دوره هکرقانونمند با دیدگاهی متفاوت و تجربی | CEH V11",
    desc: "یکی از دوره هایی که در مسیر یادگیری هک و امنیت باید بهش مراجعه کنید. دوره CEH هس...",
    name: "اشکان مقدس",
    time: "43:46",
    price: 2_300_000,
    member: 631,
    image: doreHakere,
    type: "security",
  },
  {
    id: 30,
    tag1: "امنیت",
    title: "آموزش ابزار Burp Suite در دنیای واقعی",
    desc: "اگر شما مراحل مقدماتی تست نفوذ وب رو مثل آشنایی با آسیب پذیری ها رو گذرونده باشی الان...",
    name: "mV.arman",
    time: "07:40",
    price: 899_000,
    member: 10422,
    image: burpSuite,
    type: "security",
  },
  {
    id: 31,
    tag1: "امنیت",
    tag2: "پایتون",
    title: "آموزش پایتون با گرایش امنیت | پایتون سیاه",
    desc: "زبان برنامه نویسی پایتون بخاطر سادگی. قدرت. و جامعه اماری بالایی که داره تونسته جز محبو...",
    name: "قدیر یلمه",
    time: "52:43",
    price: 864_000,
    member: 1295,
    image: amozeshPythonBaGerayesh,
    type: "security",
  },
  {
    id: 32,
    tag1: "امنیت",
    title: "آموزش جاوااسکریپت با گرایش امنیت | جاوااسکریپت سیاه",
    desc: "جاوااسکریپت همواره در لیست محبوب ترین زبان های برنامه نویسی برای هکرها و امنیت کارهاس...",
    name: "قدیر یلمه",
    time: "17:20",
    price: "رایگان",
    member: 23494,
    image: jsSiahImg,
    type: "security",
  },
  {
    id: 33,
    tag1: "بک اند",
    tag2: "پایتون",
    title: "دوره پروژه محور متخصص جنگو",
    desc: " از ویژگی های مهم دوره آموزش جنگو میتونیم به توضیح کامل مفاهیم پایه و ساختاری، کامل..",
    name: "رضا دولتی",
    time: "47:22",
    price: 3_500_000,
    member: 478,
    image: jangoImg,
    type: "python",
  },
  {
    id: 34,
    tag1: "پایتون",
    title: "Data Visualization با پایتون",
    desc: " ما تو دنیایی زندگی میکنیم که همه چیز به سمت سریع تر شدن حرکت میکنه. برای ذهن انسان...",
    name: "رضا دولتی",
    time: "04:13",
    price: 619_500,
    member: 261,
    image: DataVisualization,
    type: "python",
  },
  {
    id: 35,
    tag1: "پایتون",
    title: "بهینه نویسی کد ها در پایتون",
    desc: "همه میدونیم که زبان برنامه نویسی پایتون یه زبان خیلی جذاب، راحت و همینطور کاربردیه. ...",
    name: "رضا دولتی",
    time: "08:46",
    price: 540_000,
    member: 490,
    image: behinePython,
    type: "python",
  },
  {
    id: 36,
    tag1: "پایتون",
    title: "پروژه های کاربردی با پایتون",
    desc: "قبل از اینکه بخواین این دوره رو ببینید اگر دوره آموزش پایتون رو ندیدین حتما دوره رو ببینید...",
    name: "رضا دولتی",
    time: "15:17",
    price: 990_000,
    member: 1318,
    image: pythonProject,
    type: "python",
  },
  {
    id: 37,
    tag1: "پایتون",
    title: "آموزش پایتون رایگان مقدماتی تا پیشرفته + پروژه های جذاب",
    desc: "حیف نیست محبوب ترین زبان برنامه نویسی دنیا رو  ناقص و بی هدف یادبگیری؟ ما تصمیم...",
    name: "رضا دولتی",
    time: "77:50",
    price: "رایگان",
    member: 68386,
    image: motekhassesPytonImg,
    type: "python",
  },
  {
    id: 38,
    tag1: "امنیت",
    tag2: "پایتون",
    title: "آموزش پایتون با گرایش امنیت | پایتون سیاه",
    desc: "زبان برنامه نویسی پایتون بخاطر سادگی. قدرت. و جامعه اماری بالایی که داره تونسته جز محبو...",
    name: "قدیر یلمه",
    time: "52:43",
    price: 864_000,
    member: 1295,
    image: amozeshPythonBaGerayesh,
    type: "python",
  },
  {
    id: 39,
    tag1: "بک اند",
    tag2: "پی اچ پی",
    title: "دوره پروژه محور لایووایر (Livewire Master)",
    desc: "دوره لایووایر مستر (Livewire Master) یک دوره‌ی تمام عیار برای فول‌استک فریمورکِ...",
    name: "آرمین هوشمند",
    time: "01:24",
    price: 699_000,
    member: 25,
    image: liveVierMasterImg,
    type: "php",
  },
  {
    id: 40,
    tag1: "بک اند",
    tag2: "پی اچ پی",
    title: "144 تابع کالکشن در Laravel",
    desc: "کالکشن ها در لاراول به شما این امکان را میدهند که تمام نیاز های خود را هنگام کار با...",
    name: "آرمین هوشمند",
    time: "01:35",
    price: 699_000,
    member: 3258,
    image: laravelImg,
    type: "php",
  },
  {
    id: 41,
    tag1: "بک اند",
    tag2: "پی اچ پی",
    title: "آموزش ساخت ربات تلگرام با PHP",
    desc: 'توی دوره فوق‌العاده جذاب و کاربردی "ربات تلگرام با PHP"، به دنیای عجیب و جذاب ربات نویس...',
    name: "معین باغشیخی",
    time: "01:48",
    price: 450_000,
    member: 170,
    image: robotTelegramImg,
    type: "php",
  },
  {
    id: 42,
    tag1: "بک اند",
    tag2: "پی اچ پی",
    title: "پروژه های کاربردی با PHP",
    desc: '"مینی پروژه‌های کاربری با PHP" یه دوره آموزشی گام به گام هست که برای توسعه‌دهندگان وب،...',
    name: "معین باغشیخی",
    time: "10:01",
    price: "رایگان",
    member: 7478,
    image: phpImg,
    type: "php",
  },
  {
    id: 43,
    tag1: "ارتقای مهارت ها",
    title: "آموزش پروژه محور WebSocket",
    desc: '"با Socket می‌تونی مثل تلگرام یا سایت های ارز دیجیتال یه ارتباط Realtime بسازی و بدون نیاز...',
    name: "محمدامین سعیدی راد",
    time: "00:19",
    price: 1_190_000,
    member: 59,
    image: webSocketImg,
    type: "levelup",
  },
  {
    id: 44,
    tag1: "ارتقای مهارت ها",
    title: "آموزش جامع پروژه محور GraphQL",
    desc: "واسه حرفه‌ای‌تر شدن و استخدام تو شرکت های بزرگ با حقوق های بالا باید Graph رو بلد باشی",
    name: "محمدامین سعیدی راد",
    time: "00:15",
    price: 970_000,
    member: 48,
    image: graphQlImg,
    type: "levelup",
  },
  {
    id: 45,
    tag1: "ارتقای مهارت ها",
    tag2: "فرانت اند",
    title: "توسعه کتابخانه با جاوااسکریپت",
    desc: "توسعه کتابخانه، نمونه کاری قوی برای رزومه شما است و این دوره آموزشی یادگیری چنین مهارتی",
    name: "مهرشاد براتی",
    time: "00:15",
    price: 1_100_000,
    member: 39,
    image: toseeKetabKhaneImg,
    type: "levelup",
  },
  {
    id: 46,
    tag1: "ارتقای مهارت ها",
    tag2: "فرانت اند",
    title: "توسعه افزونه مرورگر با جاوااسکریپت",
    desc: "ما در این دوره، توسعه افزونه های مرورگر رو با پیاده سازی پروژه های کاربردی با دانش فرانت ان",
    name: "مهرشاد براتی",
    time: "00:15",
    price: 790_000,
    member: 58,
    image: afzooneMororGarImg,
    type: "levelup",
  },
  {
    id: 47,
    tag1: "ارتقای مهارت ها",
    title: "آموزش الگوریتم و ساختمان داده به زبان ساده",
    desc: "الگوریتم، یک مهارت ضروری برای ورود به دنیای برنامه نویسیه که دیدگاه شما رو به مسائل...",
    name: "رضا دولتی",
    time: "00:26",
    price: 2_300_000,
    member: 374,
    image: algoritmBeZabanSade,
    type: "levelup",
  },
  {
    id: 48,
    tag1: "ارتقای مهارت ها",
    title: "زیر و بَم و منطق دیپلوی برای برنامه نویسان JS",
    desc: "تو هر فیلدی فعالیت بکنی برای پرزنت خودت تو بازار کار و نمایش نمونه کارات نیاز به دپلوی...",
    name: "محمدامین سعیدی راد",
    time: "00:19",
    price: 700_000,
    member: 221,
    image: deeoloyImg,
    type: "levelup",
  },
  {
    id: 49,
    tag1: "ارتقای مهارت ها",
    title: "Clean Code برای برنامه نویسان JS",
    desc: "فرق بین یه برنامه‌نویس تازه‌کار و حرفه‌ای نوع دیدگاه و طرز کدنویسیشونه. برنامه‌نویس...",
    name: "محمدامین سعیدی راد",
    time: "03:52",
    price: 1_100_000,
    member: 235,
    image: cleanCodeImg,
    type: "levelup",
  },
  {
    id: 50,
    tag1: "ارتقای مهارت ها",
    title: "آموزش git و github",
    desc: "گیت یه Version Controller هست که نسخه های مختلف پروژه هامون رو مدیریت و نگهداری...",
    name: "محمدامین سعیدی راد",
    time: "12:26",
    price: 690_000,
    member: 1012,
    image: git,
    type: "levelup",
  },
  {
    id: 51,
    tag1: "ارتقای مهارت ها",
    tag2: "بک اند",
    title: "دوره حرفه ای MERN STACK",
    desc: "کلمه MERN مخفف 4 تکنولوژی Mongo , Express , React , Node بوده و بین استک ها...",
    name: "محمدامین سعیدی راد",
    time: "03:06",
    price: 1_245_000,
    member: 124,
    image: mernStack,
    type: "levelup",
  },
  {
    id: 52,
    tag1: "ارتقای مهارت ها",
    title: "آموزش اصولی RegEX برای تمام برنامه نویسان",
    desc: "RegEx یک زبان یا فریمورک جدا از زبان برنامه نویسی نیست. بلکه یک تکنولوژی و سینتکس...",
    name: "محمدامین سعیدی راد",
    time: "05:22",
    price: 240_000,
    member: 885,
    image: regex,
    type: "levelup",
  },
  {
    id: 53,
    tag1: "ارتقای مهارت ها",
    title: "آموزش NPM برای جاوااسکریپت کارها",
    desc: "به صورت خلاصه، NPM یک پکیج منیجر است. در اصل نود جی اس یک پکیج منیجر به اسم...",
    name: "محمدامین سعیدی راد",
    time: "03:49",
    price: "رایگان",
    member: 16590,
    image: npm,
    type: "levelup",
  },
  {
    id: 54,
    tag1: "ارتقای مهارت ها",
    title: "آموزش کاربردی Vscode | مقدماتی تا پیشرفته",
    desc: "اگر در گروه های برنامه نویسی موجود در شبکه های مجازی مختلف حضور داشته باشید، قطعا...",
    name: "محمدامین سعیدی راد",
    time: "05:14",
    price: "رایگان",
    member: 20160,
    image: vsCode,
    type: "levelup",
  },
];

export default CoursesData;
